import { Inter } from "next/font/google";
import "./globals.css";
import {ThirdwebProvider} from "thirdweb/react";
import {ConnectWallet} from "@thirdweb-dev/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
      <body className={inter.className}>
      <ThirdwebProvider>
          <ConnectWallet />
        {children}
      </ThirdwebProvider>
      </body>
      </html>
  );

}
